name: 'Run E2E Tests'

description: 'Sets up a test environment with a specific manager and SDK version, then runs Vitest'

inputs:
  manager_version:
    description: 'Manager version to test (e.g., 1.5.2), Leave blank for latest'
    required: false
    default: ''
  sdk_version:
    description: 'SDK version to test (e.g., 0.8.1), Leave blank for latest'
    required: false
    default: ''

runs:
  using: composite
  steps:
    # Step 1: Get the latest manager version using a dedicated action if no input is provided.
    - name: Get latest manager version
      if: inputs.manager_version == ''
      id: get_manager_version
      shell: bash
      run: |
        LATEST_TAG=$(curl -s https://api.github.com/repos/MapColonies/jobnik-manager/releases/latest | jq -r .tag_name)
        echo "Latest manager tag found: $LATEST_TAG"
        echo "version=$LATEST_TAG" >> $GITHUB_OUTPUT
    
    # Step 2: Get the latest SDK version using a dedicated action if no input is provided.
    - name: Get latest sdk version
      if: inputs.sdk_version == ''
      id: get_sdk_version
      shell: bash
      run: |
        LATEST_TAG=$(curl -s https://api.github.com/repos/MapColonies/jobnik-sdk/releases/latest | jq -r .tag_name)
        echo "Latest sdk tag found: $LATEST_TAG"
        echo "version=$LATEST_TAG" >> $GITHUB_OUTPUT
        
    # Step 3: Checkout the manager's source code to be built by Docker Compose.
    - name: Checkout Manager Source Code
      uses: actions/checkout@v5
      with:
        repository: MapColonies/jobnik-manager
        ref: ${{ inputs.manager_version || steps.get_manager_version.outputs.version }}
        path: jobnik-manager
    
    # Step 4: Build, deploy, and wait for services to be healthy using Docker's native functionality.
    - name: Build and Deploy the Services
      run: docker compose up --build -d --wait
      shell: bash

    # Step 5: Checkout the SDK's source code to be packed.
    - name: Checkout SDK Source Code
      uses: actions/checkout@v5
      with:
        repository: MapColonies/jobnik-sdk
        ref: ${{ inputs.sdk_version || steps.get_sdk_version.outputs.version }}
        path: jobnik-sdk

    # Step 6: Set up the Node.js runtime environment for testing.
    - name: Setup Node.js environment
      uses: actions/setup-node@v5
      with:
        node-version: '22.x'
        cache: 'npm'
    
    # Step 6: Install dependencies and run the tests.
    # Using 'run' with shell is the standard way to execute npm commands.
    - name: Install Dependencies and Run Tests
      shell: bash
      env:
        MANAGER_API_URL: http://localhost:8080 
        CI: true
      run: |
        PACKED_FILE_NAME = $(npm pack ./jobnik-sdk --pack-destination . --json | jq -r '.[0].filename')
        echo "packed file name = $PACKED_FILE_NAME"
        npm install "./$PACKED_FILE_NAME"
        npm ci
        npm test
