name: 'Run E2E Tests'

description: 'Sets up a test environment with a specific manager and SDK version, then runs Vitest'

inputs:
  manager_version:
    description: 'Manager version to test (e.g., 1.5.2). Leave blank for latest commit on master.'
    required: false
    default: ''
  sdk_version:
    description: 'SDK version to test (e.g., 1.5.2). Leave blank for latest commit on master.'
    required: false
    default: ''

runs:
  using: composite
  steps:
    # Step 1: Checkout this repo which contains the action and docker-compose file
    - name: Checkout E2E repository
      uses: actions/checkout@v5
      with:
        repository: MapColonies/jobnik-e2e

    # Step 2: Checkout the manager's source code
    - name: Checkout Manager Source Code
      uses: actions/checkout@v5
      with:
        repository: MapColonies/jobnik-manager
        ref: ${{ inputs.manager_version || 'master' }}
        path: jobnik-manager
    
    # Step 3: Build, deploy, and wait for services to be healthy
    - name: Build and Deploy the Services
      run: docker compose up --build --wait
      shell: bash

    # Step 4: Checkout the SDK's source code
    - name: Checkout SDK Source Code
      uses: actions/checkout@v5
      with:
        repository: MapColonies/jobnik-sdk
        ref: ${{ inputs.sdk_version || 'master' }}
        path: jobnik-sdk

    # Step 5: Set up the Node.js runtime environment for testing
    - name: Setup Node.js environment
      uses: actions/setup-node@v6
      with:
        node-version: '24.x'
        cache: 'npm'

    # Step 6: Install dependencies for jobnik-sdk and pack it
    - name: Install jobnik-sdk dependencies
      shell: bash
      working-directory: ./jobnik-sdk
      run: npm ci
    
    # Step 7: Install dependencies and run the tests
    - name: Install Dependencies and Run Tests
      shell: bash
      env:
        JOBNIK_MANAGER_BASE_URL: http://localhost:8080 
        CI: true
      run: |
        PACKED_FILE_NAME=$(npm pack ./jobnik-sdk --pack-destination . --json | jq -r '.[0].filename')
        echo "Packed File Name: $PACKED_FILE_NAME"
        npm install "./$PACKED_FILE_NAME"
        npm ci
        npm test
